package com.fasttrack.app.theme

import androidx.compose.ui.graphics.Color

// Light Theme — Teal / Emerald
val md_theme_light_primary = Color(0xFF006B5E)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFF7DF8E1)
val md_theme_light_onPrimaryContainer = Color(0xFF00201B)
val md_theme_light_secondary = Color(0xFF4B635D)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFCDE8E0)
val md_theme_light_onSecondaryContainer = Color(0xFF06201B)
val md_theme_light_tertiary = Color(0xFF416278)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFC5E7FF)
val md_theme_light_onTertiaryContainer = Color(0xFF001E2F)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_background = Color(0xFFF5FBF7)
val md_theme_light_onBackground = Color(0xFF171D1B)
val md_theme_light_surface = Color(0xFFF5FBF7)
val md_theme_light_onSurface = Color(0xFF171D1B)
val md_theme_light_surfaceVariant = Color(0xFFDAE5E0)
val md_theme_light_onSurfaceVariant = Color(0xFF3F4945)
val md_theme_light_outline = Color(0xFF6F7975)
val md_theme_light_outlineVariant = Color(0xFFBEC9C4)

// Dark Theme — Teal / Emerald
val md_theme_dark_primary = Color(0xFF5EDBC5)
val md_theme_dark_onPrimary = Color(0xFF003830)
val md_theme_dark_primaryContainer = Color(0xFF005047)
val md_theme_dark_onPrimaryContainer = Color(0xFF7DF8E1)
val md_theme_dark_secondary = Color(0xFFB1CCC4)
val md_theme_dark_onSecondary = Color(0xFF1D352F)
val md_theme_dark_secondaryContainer = Color(0xFF334B46)
val md_theme_dark_onSecondaryContainer = Color(0xFFCDE8E0)
val md_theme_dark_tertiary = Color(0xFFA9CBE3)
val md_theme_dark_onTertiary = Color(0xFF0F3447)
val md_theme_dark_tertiaryContainer = Color(0xFF294A5F)
val md_theme_dark_onTertiaryContainer = Color(0xFFC5E7FF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_background = Color(0xFF0F1513)
val md_theme_dark_onBackground = Color(0xFFDEE4E0)
val md_theme_dark_surface = Color(0xFF0F1513)
val md_theme_dark_onSurface = Color(0xFFDEE4E0)
val md_theme_dark_surfaceVariant = Color(0xFF3F4945)
val md_theme_dark_onSurfaceVariant = Color(0xFFBEC9C4)
val md_theme_dark_outline = Color(0xFF89938F)
val md_theme_dark_outlineVariant = Color(0xFF3F4945)

// Timer-specific colors
val TimerGradientStart = Color(0xFF00BFA5)
val TimerGradientEnd = Color(0xFF00E676)
val TimerGradientStartDark = Color(0xFF5EDBC5)
val TimerGradientEndDark = Color(0xFF69F0AE)
val TimerTrackLight = Color(0xFFE0E0E0)
val TimerTrackDark = Color(0xFF2C2C2C)

// Stage colors
val StageCompleted = Color(0xFF4CAF50)
